# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 14:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('no_of_players', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='SUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('enthu_level', models.IntegerField()),
                ('play_time', models.IntegerField()),
                ('interests', models.ManyToManyField(blank=True, to='rest_api.Sport')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
