# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='enthu_level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='suser',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suser',
            name='long',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='suser',
            name='play_time',
            field=models.IntegerField(blank=True),
        ),
    ]
