# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20161121_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='expertise_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suser',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suser',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
