# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20161121_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='enthu_level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='suser',
            name='expertise_level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='suser',
            name='play_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='suser',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='suser',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
